env:
  RUBY_VERSION: 2.7
  NODE_VERSION: 12
  RAILS_ENV: test
  POSTGRES_PASSWORD: "postgres"

name: Continuous Integration
on: [push, pull_request]

jobs:
  bundle_install:
    name: Setup Ruby and bundle install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Cache Ruby gems
        uses: actions/cache@v2
        id: bundler-cache
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}

      - name: Bundle install
        if: steps.bundler-cache.outputs.cache-hit != 'true'
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

  rubocop:
    name: Rubocop
    needs: bundle_install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Restore cache for Ruby gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}

      - name: Use gems from vendor/bundle
        run: bundle config path vendor/bundle

      - name: Run Rubocop
        run: bundle exec rubocop -p

  test:
    name: Rails tests
    needs: bundle_install
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Restore cache for Ruby gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}

      - name: Use gems from vendor/bundle
        run: bundle config path vendor/bundle

      - name: Create master.key
        env:
          RAILS_MASTER_KEY_FOR_TEST: ${{ secrets.RAILS_MASTER_KEY_FOR_TEST }}
        run: echo "${RAILS_MASTER_KEY_FOR_TEST}" > ./config/master.key

      - name: Setup database
        run: |
          cp ./.github/workflows/templates/database.yml.github-actions config/database.yml
          bin/rails db:test:prepare

      - name: bin/rails test
        run: bin/rails test
